
interface _GlobalComponents {
      'AutomaticImgTaker': typeof import("../components/AutomaticImgTaker.vue")['default']
    'ButtonArrowBtn': typeof import("../components/Button/ArrowBtn.vue")['default']
    'ButtonBack': typeof import("../components/Button/Back.vue")['default']
    'ButtonChevron': typeof import("../components/Button/Chevron.vue")['default']
    'ButtonDarkMode': typeof import("../components/Button/DarkMode.vue")['default']
    'ButtonDot': typeof import("../components/Button/Dot.vue")['default']
    'ButtonExpand': typeof import("../components/Button/Expand.vue")['default']
    'ButtonLarge': typeof import("../components/Button/Large.vue")['default']
    'ButtonLogin': typeof import("../components/Button/Login.vue")['default']
    'ButtonMapToggle': typeof import("../components/Button/MapToggle.vue")['default']
    'ButtonNav': typeof import("../components/Button/Nav.vue")['default']
    'ButtonPrimary': typeof import("../components/Button/Primary.vue")['default']
    'ButtonProfile': typeof import("../components/Button/Profile.vue")['default']
    'ButtonProfileBtn': typeof import("../components/Button/ProfileBtn.vue")['default']
    'ButtonResetPass': typeof import("../components/Button/ResetPass.vue")['default']
    'ButtonSecondary': typeof import("../components/Button/Secondary.vue")['default']
    'ButtonSquare': typeof import("../components/Button/Square.vue")['default']
    'ButtonToggle copy': typeof import("../components/Button/Toggle copy.vue")['default']
    'ButtonToggle': typeof import("../components/Button/Toggle.vue")['default']
    'ButtonWithIcon': typeof import("../components/Button/WithIcon.vue")['default']
    'ButtonWithIcon2': typeof import("../components/Button/WithIcon2.vue")['default']
    'CardsEventCategory': typeof import("../components/Cards/EventCategory.vue")['default']
    'CardsGroupMsg': typeof import("../components/Cards/GroupMsg.vue")['default']
    'CardsHost': typeof import("../components/Cards/Host.vue")['default']
    'CardsLgProfile': typeof import("../components/Cards/LgProfile.vue")['default']
    'CardsLocation': typeof import("../components/Cards/Location.vue")['default']
    'CardsMessage': typeof import("../components/Cards/Message.vue")['default']
    'CardsNotification': typeof import("../components/Cards/Notification.vue")['default']
    'CardsNotification2': typeof import("../components/Cards/Notification2.vue")['default']
    'CardsOffer': typeof import("../components/Cards/Offer.vue")['default']
    'CardsProfile copy': typeof import("../components/Cards/Profile copy.vue")['default']
    'CardsProfile': typeof import("../components/Cards/Profile.vue")['default']
    'CardsProfile2': typeof import("../components/Cards/Profile2.vue")['default']
    'CardsProfile3': typeof import("../components/Cards/Profile3.vue")['default']
    'CommonActioncell': typeof import("../components/Common/Actioncell.vue")['default']
    'CommonBreadcumb': typeof import("../components/Common/Breadcumb.vue")['default']
    'CommonDotPaginator': typeof import("../components/Common/DotPaginator.vue")['default']
    'CommonSimpleTimer': typeof import("../components/Common/SimpleTimer.vue")['default']
    'CommonSlider': typeof import("../components/Common/Slider.vue")['default']
    'CommonSpinner': typeof import("../components/Common/Spinner.vue")['default']
    'CommonTab': typeof import("../components/Common/Tab.vue")['default']
    'CommonTable': typeof import("../components/Common/Table.vue")['default']
    'CommonTimer': typeof import("../components/Common/Timer.vue")['default']
    'ContainerAnimationPulse': typeof import("../components/Container/AnimationPulse.vue")['default']
    'ContainerCardScroller': typeof import("../components/Container/CardScroller.vue")['default']
    'ContainerDetails': typeof import("../components/Container/Details.vue")['default']
    'ContainerDiscount': typeof import("../components/Container/Discount.vue")['default']
    'ContainerEventDetails': typeof import("../components/Container/Event/Details.vue")['default']
    'ContainerEventDetailsCommon': typeof import("../components/Container/Event/DetailsCommon.vue")['default']
    'ContainerEventDetailsCommon2': typeof import("../components/Container/Event/DetailsCommon2.vue")['default']
    'ContainerEventDetailsSelfSmall': typeof import("../components/Container/Event/DetailsSelfSmall.vue")['default']
    'ContainerEventDetailsSmall': typeof import("../components/Container/Event/DetailsSmall.vue")['default']
    'ContainerEventEditSmall': typeof import("../components/Container/Event/EditSmall.vue")['default']
    'ContainerEventFinding': typeof import("../components/Container/Event/Finding.vue")['default']
    'ContainerEventParticipants': typeof import("../components/Container/Event/Participants.vue")['default']
    'ContainerEventParticipantsCommon': typeof import("../components/Container/Event/ParticipantsCommon.vue")['default']
    'ContainerEventSelfDetailsSmall': typeof import("../components/Container/Event/SelfDetailsSmall.vue")['default']
    'ContainerEventImg': typeof import("../components/Container/EventImg.vue")['default']
    'ContainerEventImg2': typeof import("../components/Container/EventImg2.vue")['default']
    'ContainerForgetPassword': typeof import("../components/Container/ForgetPassword.vue")['default']
    'ContainerFriendsGallary': typeof import("../components/Container/Friends/Gallary.vue")['default']
    'ContainerFriendsRequest': typeof import("../components/Container/Friends/Request.vue")['default']
    'ContainerGallarySlider': typeof import("../components/Container/GallarySlider.vue")['default']
    'ContainerGroupProfile': typeof import("../components/Container/GroupProfile.vue")['default']
    'ContainerHorizontal': typeof import("../components/Container/Horizontal.vue")['default']
    'ContainerHowWorks': typeof import("../components/Container/HowWorks.vue")['default']
    'ContainerImagesUploader': typeof import("../components/Container/ImagesUploader.vue")['default']
    'ContainerLogin': typeof import("../components/Container/Login.vue")['default']
    'ContainerMeetup': typeof import("../components/Container/Meetup.vue")['default']
    'ContainerMessageBox': typeof import("../components/Container/Message/Box.vue")['default']
    'ContainerProfile': typeof import("../components/Container/Profile.vue")['default']
    'ContainerProfileAbout': typeof import("../components/Container/Profile/About.vue")['default']
    'ContainerProfileDetailsSmall': typeof import("../components/Container/Profile/DetailsSmall.vue")['default']
    'ContainerProfileHabits': typeof import("../components/Container/Profile/Habits.vue")['default']
    'ContainerProfileImage': typeof import("../components/Container/Profile/Image.vue")['default']
    'ContainerProfileInterests': typeof import("../components/Container/Profile/Interests.vue")['default']
    'ContainerProfileLeftSideSection': typeof import("../components/Container/Profile/LeftSideSection.vue")['default']
    'ContainerProfileName': typeof import("../components/Container/Profile/Name.vue")['default']
    'ContainerProfilePhotos': typeof import("../components/Container/Profile/Photos.vue")['default']
    'ContainerProfilePublicDetailsSmall': typeof import("../components/Container/Profile/PublicDetailsSmall.vue")['default']
    'ContainerProfileSummery': typeof import("../components/Container/Profile/Summery.vue")['default']
    'ContainerProfileImagesUploader': typeof import("../components/Container/ProfileImagesUploader.vue")['default']
    'ContainerRegister copy': typeof import("../components/Container/Register copy.vue")['default']
    'ContainerRegister': typeof import("../components/Container/Register.vue")['default']
    'ContainerSlider': typeof import("../components/Container/Slider.vue")['default']
    'ContainerStories': typeof import("../components/Container/Stories.vue")['default']
    'ContainerTestimonial copy': typeof import("../components/Container/Testimonial copy.vue")['default']
    'ContainerTestimonial': typeof import("../components/Container/Testimonial.vue")['default']
    'ContainerUniversalSearch': typeof import("../components/Container/UniversalSearch.vue")['default']
    'ContainerUserDetails': typeof import("../components/Container/UserDetails.vue")['default']
    'EventFilter': typeof import("../components/Event/Filter.vue")['default']
    'EventGoingPeople': typeof import("../components/Event/GoingPeople.vue")['default']
    'EventMap': typeof import("../components/Event/Map.vue")['default']
    'EventSelf': typeof import("../components/Event/Self.vue")['default']
    'EventSidebar': typeof import("../components/Event/Sidebar.vue")['default']
    'FormAgepicker': typeof import("../components/Form/Agepicker.vue")['default']
    'FormCheckbox': typeof import("../components/Form/Checkbox.vue")['default']
    'FormCombobox': typeof import("../components/Form/Combobox.vue")['default']
    'FormContainer': typeof import("../components/Form/Container.vue")['default']
    'FormDate': typeof import("../components/Form/Date.vue")['default']
    'FormDateTimepicker': typeof import("../components/Form/DateTimepicker.vue")['default']
    'FormDatepicker': typeof import("../components/Form/Datepicker.vue")['default']
    'FormDropdown': typeof import("../components/Form/Dropdown.vue")['default']
    'FormEventCreationSelector': typeof import("../components/Form/EventCreationSelector.vue")['default']
    'FormEventSelector': typeof import("../components/Form/EventSelector.vue")['default']
    'FormEventSelector2': typeof import("../components/Form/EventSelector2.vue")['default']
    'FormImage': typeof import("../components/Form/Image.vue")['default']
    'FormImage2 copy': typeof import("../components/Form/Image2 copy.vue")['default']
    'FormImage2': typeof import("../components/Form/Image2.vue")['default']
    'FormImageSelector': typeof import("../components/Form/ImageSelector.vue")['default']
    'FormInputNumber': typeof import("../components/Form/InputNumber.vue")['default']
    'FormInputText': typeof import("../components/Form/InputText.vue")['default']
    'FormInputText2': typeof import("../components/Form/InputText2.vue")['default']
    'FormInputWithDropdown': typeof import("../components/Form/InputWithDropdown.vue")['default']
    'FormMap copy 2': typeof import("../components/Form/Map copy 2.vue")['default']
    'FormMap copy': typeof import("../components/Form/Map copy.vue")['default']
    'FormMap': typeof import("../components/Form/Map.vue")['default']
    'FormMap2': typeof import("../components/Form/Map2.vue")['default']
    'FormMultipleSelect': typeof import("../components/Form/MultipleSelect.vue")['default']
    'FormMultipleSelect2': typeof import("../components/Form/MultipleSelect2.vue")['default']
    'FormOtp': typeof import("../components/Form/Otp.vue")['default']
    'FormPassword': typeof import("../components/Form/Password.vue")['default']
    'FormPermission': typeof import("../components/Form/Permission.vue")['default']
    'FormPermission2': typeof import("../components/Form/Permission2.vue")['default']
    'FormRangeSlider': typeof import("../components/Form/RangeSlider.vue")['default']
    'FormSelector': typeof import("../components/Form/Selector.vue")['default']
    'FormSelector2': typeof import("../components/Form/Selector2.vue")['default']
    'FormSelector3': typeof import("../components/Form/Selector3.vue")['default']
    'FormSelector4': typeof import("../components/Form/Selector4.vue")['default']
    'FormSelector5': typeof import("../components/Form/Selector5.vue")['default']
    'FormTextArea': typeof import("../components/Form/TextArea.vue")['default']
    'FormTimeCombobox copy': typeof import("../components/Form/TimeCombobox copy.vue")['default']
    'FormTimeCombobox': typeof import("../components/Form/TimeCombobox.vue")['default']
    'FormTimepicker': typeof import("../components/Form/Timepicker.vue")['default']
    'IconsCalender': typeof import("../components/Icons/Calender.vue")['default']
    'IconsFriends': typeof import("../components/Icons/Friends.vue")['default']
    'IconsMessage': typeof import("../components/Icons/Message.vue")['default']
    'IconsNotification': typeof import("../components/Icons/Notification.vue")['default']
    'IconsProfile': typeof import("../components/Icons/Profile.vue")['default']
    'ImgRecognizer copy 2': typeof import("../components/ImgRecognizer copy 2.vue")['default']
    'ImgRecognizer copy': typeof import("../components/ImgRecognizer copy.vue")['default']
    'ImgRecognizer': typeof import("../components/ImgRecognizer.vue")['default']
    'ImgTaker': typeof import("../components/ImgTaker.vue")['default']
    'LoaderCircle': typeof import("../components/Loader/Circle.vue")['default']
    'LoaderImgTake': typeof import("../components/Loader/ImgTake.vue")['default']
    'LoaderUniversal': typeof import("../components/Loader/Universal.vue")['default']
    'Map': typeof import("../components/Map.vue")['default']
    'MarkerPopup': typeof import("../components/MarkerPopup.vue")['default']
    'ModalContainer': typeof import("../components/Modal/Container.vue")['default']
    'ModalDelete': typeof import("../components/Modal/Delete.vue")['default']
    'ModalFilter': typeof import("../components/Modal/Filter.vue")['default']
    'ModalPhotoviewer': typeof import("../components/Modal/Photoviewer.vue")['default']
    'ModalRegistrationContainer': typeof import("../components/Modal/RegistrationContainer.vue")['default']
    'PageFooter': typeof import("../components/Page/Footer.vue")['default']
    'PageHeader': typeof import("../components/Page/Header.vue")['default']
    'PageHeaderSmall': typeof import("../components/Page/HeaderSmall.vue")['default']
    'PageHerosection': typeof import("../components/Page/Herosection.vue")['default']
    'PageHerosectionMobile': typeof import("../components/Page/HerosectionMobile.vue")['default']
    'PageImageSlider': typeof import("../components/Page/ImageSlider.vue")['default']
    'PageMenu': typeof import("../components/Page/Menu.vue")['default']
    'PageMenu2': typeof import("../components/Page/Menu2.vue")['default']
    'PageSearchbar': typeof import("../components/Page/Searchbar.vue")['default']
    'PageSectionHeader': typeof import("../components/Page/SectionHeader.vue")['default']
    'PageSelectionBar': typeof import("../components/Page/SelectionBar.vue")['default']
    'PageSidebar': typeof import("../components/Page/Sidebar.vue")['default']
    'PageSlider': typeof import("../components/Page/Slider.vue")['default']
    'PageVerticalImageSlider': typeof import("../components/Page/VerticalImageSlider.vue")['default']
    'Paginator': typeof import("../components/Paginator.vue")['default']
    'PanelBottom': typeof import("../components/Panel/Bottom.vue")['default']
    'SimpleImgTaker': typeof import("../components/SimpleImgTaker.vue")['default']
    'SkeletonAbout': typeof import("../components/Skeleton/About.vue")['default']
    'SkeletonCards': typeof import("../components/Skeleton/Cards.vue")['default']
    'SkeletonEventImg': typeof import("../components/Skeleton/EventImg.vue")['default']
    'SkeletonFriends': typeof import("../components/Skeleton/Friends.vue")['default']
    'SkeletonInterests': typeof import("../components/Skeleton/Interests.vue")['default']
    'SkeletonMsgBox': typeof import("../components/Skeleton/MsgBox.vue")['default']
    'SkeletonMsgGroupCards': typeof import("../components/Skeleton/MsgGroupCards.vue")['default']
    'SkeletonName': typeof import("../components/Skeleton/Name.vue")['default']
    'SkeletonParticipants': typeof import("../components/Skeleton/Participants.vue")['default']
    'SkeletonParticipantsAndDelete': typeof import("../components/Skeleton/ParticipantsAndDelete.vue")['default']
    'SkeletonPhotos': typeof import("../components/Skeleton/Photos.vue")['default']
    'SkeletonProfileImg': typeof import("../components/Skeleton/ProfileImg.vue")['default']
    'SkeletonSlider': typeof import("../components/Skeleton/Slider.vue")['default']
    'SkeletonSpinner': typeof import("../components/Skeleton/Spinner.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'FormKit': typeof import("@formkit/vue")['FormKit']
    'FormKitProvider': typeof import("@formkit/vue")['FormKitProvider']
    'FormKitMessages': typeof import("@formkit/vue")['FormKitMessages']
    'FormKitSummary': typeof import("@formkit/vue")['FormKitSummary']
    'FormKitIcon': typeof import("@formkit/vue")['FormKitIcon']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAutomaticImgTaker': typeof import("../components/AutomaticImgTaker.vue")['default']
    'LazyButtonArrowBtn': typeof import("../components/Button/ArrowBtn.vue")['default']
    'LazyButtonBack': typeof import("../components/Button/Back.vue")['default']
    'LazyButtonChevron': typeof import("../components/Button/Chevron.vue")['default']
    'LazyButtonDarkMode': typeof import("../components/Button/DarkMode.vue")['default']
    'LazyButtonDot': typeof import("../components/Button/Dot.vue")['default']
    'LazyButtonExpand': typeof import("../components/Button/Expand.vue")['default']
    'LazyButtonLarge': typeof import("../components/Button/Large.vue")['default']
    'LazyButtonLogin': typeof import("../components/Button/Login.vue")['default']
    'LazyButtonMapToggle': typeof import("../components/Button/MapToggle.vue")['default']
    'LazyButtonNav': typeof import("../components/Button/Nav.vue")['default']
    'LazyButtonPrimary': typeof import("../components/Button/Primary.vue")['default']
    'LazyButtonProfile': typeof import("../components/Button/Profile.vue")['default']
    'LazyButtonProfileBtn': typeof import("../components/Button/ProfileBtn.vue")['default']
    'LazyButtonResetPass': typeof import("../components/Button/ResetPass.vue")['default']
    'LazyButtonSecondary': typeof import("../components/Button/Secondary.vue")['default']
    'LazyButtonSquare': typeof import("../components/Button/Square.vue")['default']
    'LazyButtonToggle copy': typeof import("../components/Button/Toggle copy.vue")['default']
    'LazyButtonToggle': typeof import("../components/Button/Toggle.vue")['default']
    'LazyButtonWithIcon': typeof import("../components/Button/WithIcon.vue")['default']
    'LazyButtonWithIcon2': typeof import("../components/Button/WithIcon2.vue")['default']
    'LazyCardsEventCategory': typeof import("../components/Cards/EventCategory.vue")['default']
    'LazyCardsGroupMsg': typeof import("../components/Cards/GroupMsg.vue")['default']
    'LazyCardsHost': typeof import("../components/Cards/Host.vue")['default']
    'LazyCardsLgProfile': typeof import("../components/Cards/LgProfile.vue")['default']
    'LazyCardsLocation': typeof import("../components/Cards/Location.vue")['default']
    'LazyCardsMessage': typeof import("../components/Cards/Message.vue")['default']
    'LazyCardsNotification': typeof import("../components/Cards/Notification.vue")['default']
    'LazyCardsNotification2': typeof import("../components/Cards/Notification2.vue")['default']
    'LazyCardsOffer': typeof import("../components/Cards/Offer.vue")['default']
    'LazyCardsProfile copy': typeof import("../components/Cards/Profile copy.vue")['default']
    'LazyCardsProfile': typeof import("../components/Cards/Profile.vue")['default']
    'LazyCardsProfile2': typeof import("../components/Cards/Profile2.vue")['default']
    'LazyCardsProfile3': typeof import("../components/Cards/Profile3.vue")['default']
    'LazyCommonActioncell': typeof import("../components/Common/Actioncell.vue")['default']
    'LazyCommonBreadcumb': typeof import("../components/Common/Breadcumb.vue")['default']
    'LazyCommonDotPaginator': typeof import("../components/Common/DotPaginator.vue")['default']
    'LazyCommonSimpleTimer': typeof import("../components/Common/SimpleTimer.vue")['default']
    'LazyCommonSlider': typeof import("../components/Common/Slider.vue")['default']
    'LazyCommonSpinner': typeof import("../components/Common/Spinner.vue")['default']
    'LazyCommonTab': typeof import("../components/Common/Tab.vue")['default']
    'LazyCommonTable': typeof import("../components/Common/Table.vue")['default']
    'LazyCommonTimer': typeof import("../components/Common/Timer.vue")['default']
    'LazyContainerAnimationPulse': typeof import("../components/Container/AnimationPulse.vue")['default']
    'LazyContainerCardScroller': typeof import("../components/Container/CardScroller.vue")['default']
    'LazyContainerDetails': typeof import("../components/Container/Details.vue")['default']
    'LazyContainerDiscount': typeof import("../components/Container/Discount.vue")['default']
    'LazyContainerEventDetails': typeof import("../components/Container/Event/Details.vue")['default']
    'LazyContainerEventDetailsCommon': typeof import("../components/Container/Event/DetailsCommon.vue")['default']
    'LazyContainerEventDetailsCommon2': typeof import("../components/Container/Event/DetailsCommon2.vue")['default']
    'LazyContainerEventDetailsSelfSmall': typeof import("../components/Container/Event/DetailsSelfSmall.vue")['default']
    'LazyContainerEventDetailsSmall': typeof import("../components/Container/Event/DetailsSmall.vue")['default']
    'LazyContainerEventEditSmall': typeof import("../components/Container/Event/EditSmall.vue")['default']
    'LazyContainerEventFinding': typeof import("../components/Container/Event/Finding.vue")['default']
    'LazyContainerEventParticipants': typeof import("../components/Container/Event/Participants.vue")['default']
    'LazyContainerEventParticipantsCommon': typeof import("../components/Container/Event/ParticipantsCommon.vue")['default']
    'LazyContainerEventSelfDetailsSmall': typeof import("../components/Container/Event/SelfDetailsSmall.vue")['default']
    'LazyContainerEventImg': typeof import("../components/Container/EventImg.vue")['default']
    'LazyContainerEventImg2': typeof import("../components/Container/EventImg2.vue")['default']
    'LazyContainerForgetPassword': typeof import("../components/Container/ForgetPassword.vue")['default']
    'LazyContainerFriendsGallary': typeof import("../components/Container/Friends/Gallary.vue")['default']
    'LazyContainerFriendsRequest': typeof import("../components/Container/Friends/Request.vue")['default']
    'LazyContainerGallarySlider': typeof import("../components/Container/GallarySlider.vue")['default']
    'LazyContainerGroupProfile': typeof import("../components/Container/GroupProfile.vue")['default']
    'LazyContainerHorizontal': typeof import("../components/Container/Horizontal.vue")['default']
    'LazyContainerHowWorks': typeof import("../components/Container/HowWorks.vue")['default']
    'LazyContainerImagesUploader': typeof import("../components/Container/ImagesUploader.vue")['default']
    'LazyContainerLogin': typeof import("../components/Container/Login.vue")['default']
    'LazyContainerMeetup': typeof import("../components/Container/Meetup.vue")['default']
    'LazyContainerMessageBox': typeof import("../components/Container/Message/Box.vue")['default']
    'LazyContainerProfile': typeof import("../components/Container/Profile.vue")['default']
    'LazyContainerProfileAbout': typeof import("../components/Container/Profile/About.vue")['default']
    'LazyContainerProfileDetailsSmall': typeof import("../components/Container/Profile/DetailsSmall.vue")['default']
    'LazyContainerProfileHabits': typeof import("../components/Container/Profile/Habits.vue")['default']
    'LazyContainerProfileImage': typeof import("../components/Container/Profile/Image.vue")['default']
    'LazyContainerProfileInterests': typeof import("../components/Container/Profile/Interests.vue")['default']
    'LazyContainerProfileLeftSideSection': typeof import("../components/Container/Profile/LeftSideSection.vue")['default']
    'LazyContainerProfileName': typeof import("../components/Container/Profile/Name.vue")['default']
    'LazyContainerProfilePhotos': typeof import("../components/Container/Profile/Photos.vue")['default']
    'LazyContainerProfilePublicDetailsSmall': typeof import("../components/Container/Profile/PublicDetailsSmall.vue")['default']
    'LazyContainerProfileSummery': typeof import("../components/Container/Profile/Summery.vue")['default']
    'LazyContainerProfileImagesUploader': typeof import("../components/Container/ProfileImagesUploader.vue")['default']
    'LazyContainerRegister copy': typeof import("../components/Container/Register copy.vue")['default']
    'LazyContainerRegister': typeof import("../components/Container/Register.vue")['default']
    'LazyContainerSlider': typeof import("../components/Container/Slider.vue")['default']
    'LazyContainerStories': typeof import("../components/Container/Stories.vue")['default']
    'LazyContainerTestimonial copy': typeof import("../components/Container/Testimonial copy.vue")['default']
    'LazyContainerTestimonial': typeof import("../components/Container/Testimonial.vue")['default']
    'LazyContainerUniversalSearch': typeof import("../components/Container/UniversalSearch.vue")['default']
    'LazyContainerUserDetails': typeof import("../components/Container/UserDetails.vue")['default']
    'LazyEventFilter': typeof import("../components/Event/Filter.vue")['default']
    'LazyEventGoingPeople': typeof import("../components/Event/GoingPeople.vue")['default']
    'LazyEventMap': typeof import("../components/Event/Map.vue")['default']
    'LazyEventSelf': typeof import("../components/Event/Self.vue")['default']
    'LazyEventSidebar': typeof import("../components/Event/Sidebar.vue")['default']
    'LazyFormAgepicker': typeof import("../components/Form/Agepicker.vue")['default']
    'LazyFormCheckbox': typeof import("../components/Form/Checkbox.vue")['default']
    'LazyFormCombobox': typeof import("../components/Form/Combobox.vue")['default']
    'LazyFormContainer': typeof import("../components/Form/Container.vue")['default']
    'LazyFormDate': typeof import("../components/Form/Date.vue")['default']
    'LazyFormDateTimepicker': typeof import("../components/Form/DateTimepicker.vue")['default']
    'LazyFormDatepicker': typeof import("../components/Form/Datepicker.vue")['default']
    'LazyFormDropdown': typeof import("../components/Form/Dropdown.vue")['default']
    'LazyFormEventCreationSelector': typeof import("../components/Form/EventCreationSelector.vue")['default']
    'LazyFormEventSelector': typeof import("../components/Form/EventSelector.vue")['default']
    'LazyFormEventSelector2': typeof import("../components/Form/EventSelector2.vue")['default']
    'LazyFormImage': typeof import("../components/Form/Image.vue")['default']
    'LazyFormImage2 copy': typeof import("../components/Form/Image2 copy.vue")['default']
    'LazyFormImage2': typeof import("../components/Form/Image2.vue")['default']
    'LazyFormImageSelector': typeof import("../components/Form/ImageSelector.vue")['default']
    'LazyFormInputNumber': typeof import("../components/Form/InputNumber.vue")['default']
    'LazyFormInputText': typeof import("../components/Form/InputText.vue")['default']
    'LazyFormInputText2': typeof import("../components/Form/InputText2.vue")['default']
    'LazyFormInputWithDropdown': typeof import("../components/Form/InputWithDropdown.vue")['default']
    'LazyFormMap copy 2': typeof import("../components/Form/Map copy 2.vue")['default']
    'LazyFormMap copy': typeof import("../components/Form/Map copy.vue")['default']
    'LazyFormMap': typeof import("../components/Form/Map.vue")['default']
    'LazyFormMap2': typeof import("../components/Form/Map2.vue")['default']
    'LazyFormMultipleSelect': typeof import("../components/Form/MultipleSelect.vue")['default']
    'LazyFormMultipleSelect2': typeof import("../components/Form/MultipleSelect2.vue")['default']
    'LazyFormOtp': typeof import("../components/Form/Otp.vue")['default']
    'LazyFormPassword': typeof import("../components/Form/Password.vue")['default']
    'LazyFormPermission': typeof import("../components/Form/Permission.vue")['default']
    'LazyFormPermission2': typeof import("../components/Form/Permission2.vue")['default']
    'LazyFormRangeSlider': typeof import("../components/Form/RangeSlider.vue")['default']
    'LazyFormSelector': typeof import("../components/Form/Selector.vue")['default']
    'LazyFormSelector2': typeof import("../components/Form/Selector2.vue")['default']
    'LazyFormSelector3': typeof import("../components/Form/Selector3.vue")['default']
    'LazyFormSelector4': typeof import("../components/Form/Selector4.vue")['default']
    'LazyFormSelector5': typeof import("../components/Form/Selector5.vue")['default']
    'LazyFormTextArea': typeof import("../components/Form/TextArea.vue")['default']
    'LazyFormTimeCombobox copy': typeof import("../components/Form/TimeCombobox copy.vue")['default']
    'LazyFormTimeCombobox': typeof import("../components/Form/TimeCombobox.vue")['default']
    'LazyFormTimepicker': typeof import("../components/Form/Timepicker.vue")['default']
    'LazyIconsCalender': typeof import("../components/Icons/Calender.vue")['default']
    'LazyIconsFriends': typeof import("../components/Icons/Friends.vue")['default']
    'LazyIconsMessage': typeof import("../components/Icons/Message.vue")['default']
    'LazyIconsNotification': typeof import("../components/Icons/Notification.vue")['default']
    'LazyIconsProfile': typeof import("../components/Icons/Profile.vue")['default']
    'LazyImgRecognizer copy 2': typeof import("../components/ImgRecognizer copy 2.vue")['default']
    'LazyImgRecognizer copy': typeof import("../components/ImgRecognizer copy.vue")['default']
    'LazyImgRecognizer': typeof import("../components/ImgRecognizer.vue")['default']
    'LazyImgTaker': typeof import("../components/ImgTaker.vue")['default']
    'LazyLoaderCircle': typeof import("../components/Loader/Circle.vue")['default']
    'LazyLoaderImgTake': typeof import("../components/Loader/ImgTake.vue")['default']
    'LazyLoaderUniversal': typeof import("../components/Loader/Universal.vue")['default']
    'LazyMap': typeof import("../components/Map.vue")['default']
    'LazyMarkerPopup': typeof import("../components/MarkerPopup.vue")['default']
    'LazyModalContainer': typeof import("../components/Modal/Container.vue")['default']
    'LazyModalDelete': typeof import("../components/Modal/Delete.vue")['default']
    'LazyModalFilter': typeof import("../components/Modal/Filter.vue")['default']
    'LazyModalPhotoviewer': typeof import("../components/Modal/Photoviewer.vue")['default']
    'LazyModalRegistrationContainer': typeof import("../components/Modal/RegistrationContainer.vue")['default']
    'LazyPageFooter': typeof import("../components/Page/Footer.vue")['default']
    'LazyPageHeader': typeof import("../components/Page/Header.vue")['default']
    'LazyPageHeaderSmall': typeof import("../components/Page/HeaderSmall.vue")['default']
    'LazyPageHerosection': typeof import("../components/Page/Herosection.vue")['default']
    'LazyPageHerosectionMobile': typeof import("../components/Page/HerosectionMobile.vue")['default']
    'LazyPageImageSlider': typeof import("../components/Page/ImageSlider.vue")['default']
    'LazyPageMenu': typeof import("../components/Page/Menu.vue")['default']
    'LazyPageMenu2': typeof import("../components/Page/Menu2.vue")['default']
    'LazyPageSearchbar': typeof import("../components/Page/Searchbar.vue")['default']
    'LazyPageSectionHeader': typeof import("../components/Page/SectionHeader.vue")['default']
    'LazyPageSelectionBar': typeof import("../components/Page/SelectionBar.vue")['default']
    'LazyPageSidebar': typeof import("../components/Page/Sidebar.vue")['default']
    'LazyPageSlider': typeof import("../components/Page/Slider.vue")['default']
    'LazyPageVerticalImageSlider': typeof import("../components/Page/VerticalImageSlider.vue")['default']
    'LazyPaginator': typeof import("../components/Paginator.vue")['default']
    'LazyPanelBottom': typeof import("../components/Panel/Bottom.vue")['default']
    'LazySimpleImgTaker': typeof import("../components/SimpleImgTaker.vue")['default']
    'LazySkeletonAbout': typeof import("../components/Skeleton/About.vue")['default']
    'LazySkeletonCards': typeof import("../components/Skeleton/Cards.vue")['default']
    'LazySkeletonEventImg': typeof import("../components/Skeleton/EventImg.vue")['default']
    'LazySkeletonFriends': typeof import("../components/Skeleton/Friends.vue")['default']
    'LazySkeletonInterests': typeof import("../components/Skeleton/Interests.vue")['default']
    'LazySkeletonMsgBox': typeof import("../components/Skeleton/MsgBox.vue")['default']
    'LazySkeletonMsgGroupCards': typeof import("../components/Skeleton/MsgGroupCards.vue")['default']
    'LazySkeletonName': typeof import("../components/Skeleton/Name.vue")['default']
    'LazySkeletonParticipants': typeof import("../components/Skeleton/Participants.vue")['default']
    'LazySkeletonParticipantsAndDelete': typeof import("../components/Skeleton/ParticipantsAndDelete.vue")['default']
    'LazySkeletonPhotos': typeof import("../components/Skeleton/Photos.vue")['default']
    'LazySkeletonProfileImg': typeof import("../components/Skeleton/ProfileImg.vue")['default']
    'LazySkeletonSlider': typeof import("../components/Skeleton/Slider.vue")['default']
    'LazySkeletonSpinner': typeof import("../components/Skeleton/Spinner.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyLCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LazyLCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LazyLControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LazyLControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LazyLControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LazyLControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LazyLControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LazyLFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LazyLGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LazyLIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LazyLImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LazyLLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LazyLMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LazyLMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LazyLPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LazyLPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LazyLPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LazyLRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LazyLTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LazyLTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LazyLWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyFormKit': typeof import("@formkit/vue")['FormKit']
    'LazyFormKitProvider': typeof import("@formkit/vue")['FormKitProvider']
    'LazyFormKitMessages': typeof import("@formkit/vue")['FormKitMessages']
    'LazyFormKitSummary': typeof import("@formkit/vue")['FormKitSummary']
    'LazyFormKitIcon': typeof import("@formkit/vue")['FormKitIcon']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AutomaticImgTaker: typeof import("../components/AutomaticImgTaker.vue")['default']
export const ButtonArrowBtn: typeof import("../components/Button/ArrowBtn.vue")['default']
export const ButtonBack: typeof import("../components/Button/Back.vue")['default']
export const ButtonChevron: typeof import("../components/Button/Chevron.vue")['default']
export const ButtonDarkMode: typeof import("../components/Button/DarkMode.vue")['default']
export const ButtonDot: typeof import("../components/Button/Dot.vue")['default']
export const ButtonExpand: typeof import("../components/Button/Expand.vue")['default']
export const ButtonLarge: typeof import("../components/Button/Large.vue")['default']
export const ButtonLogin: typeof import("../components/Button/Login.vue")['default']
export const ButtonMapToggle: typeof import("../components/Button/MapToggle.vue")['default']
export const ButtonNav: typeof import("../components/Button/Nav.vue")['default']
export const ButtonPrimary: typeof import("../components/Button/Primary.vue")['default']
export const ButtonProfile: typeof import("../components/Button/Profile.vue")['default']
export const ButtonProfileBtn: typeof import("../components/Button/ProfileBtn.vue")['default']
export const ButtonResetPass: typeof import("../components/Button/ResetPass.vue")['default']
export const ButtonSecondary: typeof import("../components/Button/Secondary.vue")['default']
export const ButtonSquare: typeof import("../components/Button/Square.vue")['default']
export const ButtonToggle copy: typeof import("../components/Button/Toggle copy.vue")['default']
export const ButtonToggle: typeof import("../components/Button/Toggle.vue")['default']
export const ButtonWithIcon: typeof import("../components/Button/WithIcon.vue")['default']
export const ButtonWithIcon2: typeof import("../components/Button/WithIcon2.vue")['default']
export const CardsEventCategory: typeof import("../components/Cards/EventCategory.vue")['default']
export const CardsGroupMsg: typeof import("../components/Cards/GroupMsg.vue")['default']
export const CardsHost: typeof import("../components/Cards/Host.vue")['default']
export const CardsLgProfile: typeof import("../components/Cards/LgProfile.vue")['default']
export const CardsLocation: typeof import("../components/Cards/Location.vue")['default']
export const CardsMessage: typeof import("../components/Cards/Message.vue")['default']
export const CardsNotification: typeof import("../components/Cards/Notification.vue")['default']
export const CardsNotification2: typeof import("../components/Cards/Notification2.vue")['default']
export const CardsOffer: typeof import("../components/Cards/Offer.vue")['default']
export const CardsProfile copy: typeof import("../components/Cards/Profile copy.vue")['default']
export const CardsProfile: typeof import("../components/Cards/Profile.vue")['default']
export const CardsProfile2: typeof import("../components/Cards/Profile2.vue")['default']
export const CardsProfile3: typeof import("../components/Cards/Profile3.vue")['default']
export const CommonActioncell: typeof import("../components/Common/Actioncell.vue")['default']
export const CommonBreadcumb: typeof import("../components/Common/Breadcumb.vue")['default']
export const CommonDotPaginator: typeof import("../components/Common/DotPaginator.vue")['default']
export const CommonSimpleTimer: typeof import("../components/Common/SimpleTimer.vue")['default']
export const CommonSlider: typeof import("../components/Common/Slider.vue")['default']
export const CommonSpinner: typeof import("../components/Common/Spinner.vue")['default']
export const CommonTab: typeof import("../components/Common/Tab.vue")['default']
export const CommonTable: typeof import("../components/Common/Table.vue")['default']
export const CommonTimer: typeof import("../components/Common/Timer.vue")['default']
export const ContainerAnimationPulse: typeof import("../components/Container/AnimationPulse.vue")['default']
export const ContainerCardScroller: typeof import("../components/Container/CardScroller.vue")['default']
export const ContainerDetails: typeof import("../components/Container/Details.vue")['default']
export const ContainerDiscount: typeof import("../components/Container/Discount.vue")['default']
export const ContainerEventDetails: typeof import("../components/Container/Event/Details.vue")['default']
export const ContainerEventDetailsCommon: typeof import("../components/Container/Event/DetailsCommon.vue")['default']
export const ContainerEventDetailsCommon2: typeof import("../components/Container/Event/DetailsCommon2.vue")['default']
export const ContainerEventDetailsSelfSmall: typeof import("../components/Container/Event/DetailsSelfSmall.vue")['default']
export const ContainerEventDetailsSmall: typeof import("../components/Container/Event/DetailsSmall.vue")['default']
export const ContainerEventEditSmall: typeof import("../components/Container/Event/EditSmall.vue")['default']
export const ContainerEventFinding: typeof import("../components/Container/Event/Finding.vue")['default']
export const ContainerEventParticipants: typeof import("../components/Container/Event/Participants.vue")['default']
export const ContainerEventParticipantsCommon: typeof import("../components/Container/Event/ParticipantsCommon.vue")['default']
export const ContainerEventSelfDetailsSmall: typeof import("../components/Container/Event/SelfDetailsSmall.vue")['default']
export const ContainerEventImg: typeof import("../components/Container/EventImg.vue")['default']
export const ContainerEventImg2: typeof import("../components/Container/EventImg2.vue")['default']
export const ContainerForgetPassword: typeof import("../components/Container/ForgetPassword.vue")['default']
export const ContainerFriendsGallary: typeof import("../components/Container/Friends/Gallary.vue")['default']
export const ContainerFriendsRequest: typeof import("../components/Container/Friends/Request.vue")['default']
export const ContainerGallarySlider: typeof import("../components/Container/GallarySlider.vue")['default']
export const ContainerGroupProfile: typeof import("../components/Container/GroupProfile.vue")['default']
export const ContainerHorizontal: typeof import("../components/Container/Horizontal.vue")['default']
export const ContainerHowWorks: typeof import("../components/Container/HowWorks.vue")['default']
export const ContainerImagesUploader: typeof import("../components/Container/ImagesUploader.vue")['default']
export const ContainerLogin: typeof import("../components/Container/Login.vue")['default']
export const ContainerMeetup: typeof import("../components/Container/Meetup.vue")['default']
export const ContainerMessageBox: typeof import("../components/Container/Message/Box.vue")['default']
export const ContainerProfile: typeof import("../components/Container/Profile.vue")['default']
export const ContainerProfileAbout: typeof import("../components/Container/Profile/About.vue")['default']
export const ContainerProfileDetailsSmall: typeof import("../components/Container/Profile/DetailsSmall.vue")['default']
export const ContainerProfileHabits: typeof import("../components/Container/Profile/Habits.vue")['default']
export const ContainerProfileImage: typeof import("../components/Container/Profile/Image.vue")['default']
export const ContainerProfileInterests: typeof import("../components/Container/Profile/Interests.vue")['default']
export const ContainerProfileLeftSideSection: typeof import("../components/Container/Profile/LeftSideSection.vue")['default']
export const ContainerProfileName: typeof import("../components/Container/Profile/Name.vue")['default']
export const ContainerProfilePhotos: typeof import("../components/Container/Profile/Photos.vue")['default']
export const ContainerProfilePublicDetailsSmall: typeof import("../components/Container/Profile/PublicDetailsSmall.vue")['default']
export const ContainerProfileSummery: typeof import("../components/Container/Profile/Summery.vue")['default']
export const ContainerProfileImagesUploader: typeof import("../components/Container/ProfileImagesUploader.vue")['default']
export const ContainerRegister copy: typeof import("../components/Container/Register copy.vue")['default']
export const ContainerRegister: typeof import("../components/Container/Register.vue")['default']
export const ContainerSlider: typeof import("../components/Container/Slider.vue")['default']
export const ContainerStories: typeof import("../components/Container/Stories.vue")['default']
export const ContainerTestimonial copy: typeof import("../components/Container/Testimonial copy.vue")['default']
export const ContainerTestimonial: typeof import("../components/Container/Testimonial.vue")['default']
export const ContainerUniversalSearch: typeof import("../components/Container/UniversalSearch.vue")['default']
export const ContainerUserDetails: typeof import("../components/Container/UserDetails.vue")['default']
export const EventFilter: typeof import("../components/Event/Filter.vue")['default']
export const EventGoingPeople: typeof import("../components/Event/GoingPeople.vue")['default']
export const EventMap: typeof import("../components/Event/Map.vue")['default']
export const EventSelf: typeof import("../components/Event/Self.vue")['default']
export const EventSidebar: typeof import("../components/Event/Sidebar.vue")['default']
export const FormAgepicker: typeof import("../components/Form/Agepicker.vue")['default']
export const FormCheckbox: typeof import("../components/Form/Checkbox.vue")['default']
export const FormCombobox: typeof import("../components/Form/Combobox.vue")['default']
export const FormContainer: typeof import("../components/Form/Container.vue")['default']
export const FormDate: typeof import("../components/Form/Date.vue")['default']
export const FormDateTimepicker: typeof import("../components/Form/DateTimepicker.vue")['default']
export const FormDatepicker: typeof import("../components/Form/Datepicker.vue")['default']
export const FormDropdown: typeof import("../components/Form/Dropdown.vue")['default']
export const FormEventCreationSelector: typeof import("../components/Form/EventCreationSelector.vue")['default']
export const FormEventSelector: typeof import("../components/Form/EventSelector.vue")['default']
export const FormEventSelector2: typeof import("../components/Form/EventSelector2.vue")['default']
export const FormImage: typeof import("../components/Form/Image.vue")['default']
export const FormImage2 copy: typeof import("../components/Form/Image2 copy.vue")['default']
export const FormImage2: typeof import("../components/Form/Image2.vue")['default']
export const FormImageSelector: typeof import("../components/Form/ImageSelector.vue")['default']
export const FormInputNumber: typeof import("../components/Form/InputNumber.vue")['default']
export const FormInputText: typeof import("../components/Form/InputText.vue")['default']
export const FormInputText2: typeof import("../components/Form/InputText2.vue")['default']
export const FormInputWithDropdown: typeof import("../components/Form/InputWithDropdown.vue")['default']
export const FormMap copy 2: typeof import("../components/Form/Map copy 2.vue")['default']
export const FormMap copy: typeof import("../components/Form/Map copy.vue")['default']
export const FormMap: typeof import("../components/Form/Map.vue")['default']
export const FormMap2: typeof import("../components/Form/Map2.vue")['default']
export const FormMultipleSelect: typeof import("../components/Form/MultipleSelect.vue")['default']
export const FormMultipleSelect2: typeof import("../components/Form/MultipleSelect2.vue")['default']
export const FormOtp: typeof import("../components/Form/Otp.vue")['default']
export const FormPassword: typeof import("../components/Form/Password.vue")['default']
export const FormPermission: typeof import("../components/Form/Permission.vue")['default']
export const FormPermission2: typeof import("../components/Form/Permission2.vue")['default']
export const FormRangeSlider: typeof import("../components/Form/RangeSlider.vue")['default']
export const FormSelector: typeof import("../components/Form/Selector.vue")['default']
export const FormSelector2: typeof import("../components/Form/Selector2.vue")['default']
export const FormSelector3: typeof import("../components/Form/Selector3.vue")['default']
export const FormSelector4: typeof import("../components/Form/Selector4.vue")['default']
export const FormSelector5: typeof import("../components/Form/Selector5.vue")['default']
export const FormTextArea: typeof import("../components/Form/TextArea.vue")['default']
export const FormTimeCombobox copy: typeof import("../components/Form/TimeCombobox copy.vue")['default']
export const FormTimeCombobox: typeof import("../components/Form/TimeCombobox.vue")['default']
export const FormTimepicker: typeof import("../components/Form/Timepicker.vue")['default']
export const IconsCalender: typeof import("../components/Icons/Calender.vue")['default']
export const IconsFriends: typeof import("../components/Icons/Friends.vue")['default']
export const IconsMessage: typeof import("../components/Icons/Message.vue")['default']
export const IconsNotification: typeof import("../components/Icons/Notification.vue")['default']
export const IconsProfile: typeof import("../components/Icons/Profile.vue")['default']
export const ImgRecognizer copy 2: typeof import("../components/ImgRecognizer copy 2.vue")['default']
export const ImgRecognizer copy: typeof import("../components/ImgRecognizer copy.vue")['default']
export const ImgRecognizer: typeof import("../components/ImgRecognizer.vue")['default']
export const ImgTaker: typeof import("../components/ImgTaker.vue")['default']
export const LoaderCircle: typeof import("../components/Loader/Circle.vue")['default']
export const LoaderImgTake: typeof import("../components/Loader/ImgTake.vue")['default']
export const LoaderUniversal: typeof import("../components/Loader/Universal.vue")['default']
export const Map: typeof import("../components/Map.vue")['default']
export const MarkerPopup: typeof import("../components/MarkerPopup.vue")['default']
export const ModalContainer: typeof import("../components/Modal/Container.vue")['default']
export const ModalDelete: typeof import("../components/Modal/Delete.vue")['default']
export const ModalFilter: typeof import("../components/Modal/Filter.vue")['default']
export const ModalPhotoviewer: typeof import("../components/Modal/Photoviewer.vue")['default']
export const ModalRegistrationContainer: typeof import("../components/Modal/RegistrationContainer.vue")['default']
export const PageFooter: typeof import("../components/Page/Footer.vue")['default']
export const PageHeader: typeof import("../components/Page/Header.vue")['default']
export const PageHeaderSmall: typeof import("../components/Page/HeaderSmall.vue")['default']
export const PageHerosection: typeof import("../components/Page/Herosection.vue")['default']
export const PageHerosectionMobile: typeof import("../components/Page/HerosectionMobile.vue")['default']
export const PageImageSlider: typeof import("../components/Page/ImageSlider.vue")['default']
export const PageMenu: typeof import("../components/Page/Menu.vue")['default']
export const PageMenu2: typeof import("../components/Page/Menu2.vue")['default']
export const PageSearchbar: typeof import("../components/Page/Searchbar.vue")['default']
export const PageSectionHeader: typeof import("../components/Page/SectionHeader.vue")['default']
export const PageSelectionBar: typeof import("../components/Page/SelectionBar.vue")['default']
export const PageSidebar: typeof import("../components/Page/Sidebar.vue")['default']
export const PageSlider: typeof import("../components/Page/Slider.vue")['default']
export const PageVerticalImageSlider: typeof import("../components/Page/VerticalImageSlider.vue")['default']
export const Paginator: typeof import("../components/Paginator.vue")['default']
export const PanelBottom: typeof import("../components/Panel/Bottom.vue")['default']
export const SimpleImgTaker: typeof import("../components/SimpleImgTaker.vue")['default']
export const SkeletonAbout: typeof import("../components/Skeleton/About.vue")['default']
export const SkeletonCards: typeof import("../components/Skeleton/Cards.vue")['default']
export const SkeletonEventImg: typeof import("../components/Skeleton/EventImg.vue")['default']
export const SkeletonFriends: typeof import("../components/Skeleton/Friends.vue")['default']
export const SkeletonInterests: typeof import("../components/Skeleton/Interests.vue")['default']
export const SkeletonMsgBox: typeof import("../components/Skeleton/MsgBox.vue")['default']
export const SkeletonMsgGroupCards: typeof import("../components/Skeleton/MsgGroupCards.vue")['default']
export const SkeletonName: typeof import("../components/Skeleton/Name.vue")['default']
export const SkeletonParticipants: typeof import("../components/Skeleton/Participants.vue")['default']
export const SkeletonParticipantsAndDelete: typeof import("../components/Skeleton/ParticipantsAndDelete.vue")['default']
export const SkeletonPhotos: typeof import("../components/Skeleton/Photos.vue")['default']
export const SkeletonProfileImg: typeof import("../components/Skeleton/ProfileImg.vue")['default']
export const SkeletonSlider: typeof import("../components/Skeleton/Slider.vue")['default']
export const SkeletonSpinner: typeof import("../components/Skeleton/Spinner.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const FormKit: typeof import("@formkit/vue")['FormKit']
export const FormKitProvider: typeof import("@formkit/vue")['FormKitProvider']
export const FormKitMessages: typeof import("@formkit/vue")['FormKitMessages']
export const FormKitSummary: typeof import("@formkit/vue")['FormKitSummary']
export const FormKitIcon: typeof import("@formkit/vue")['FormKitIcon']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAutomaticImgTaker: typeof import("../components/AutomaticImgTaker.vue")['default']
export const LazyButtonArrowBtn: typeof import("../components/Button/ArrowBtn.vue")['default']
export const LazyButtonBack: typeof import("../components/Button/Back.vue")['default']
export const LazyButtonChevron: typeof import("../components/Button/Chevron.vue")['default']
export const LazyButtonDarkMode: typeof import("../components/Button/DarkMode.vue")['default']
export const LazyButtonDot: typeof import("../components/Button/Dot.vue")['default']
export const LazyButtonExpand: typeof import("../components/Button/Expand.vue")['default']
export const LazyButtonLarge: typeof import("../components/Button/Large.vue")['default']
export const LazyButtonLogin: typeof import("../components/Button/Login.vue")['default']
export const LazyButtonMapToggle: typeof import("../components/Button/MapToggle.vue")['default']
export const LazyButtonNav: typeof import("../components/Button/Nav.vue")['default']
export const LazyButtonPrimary: typeof import("../components/Button/Primary.vue")['default']
export const LazyButtonProfile: typeof import("../components/Button/Profile.vue")['default']
export const LazyButtonProfileBtn: typeof import("../components/Button/ProfileBtn.vue")['default']
export const LazyButtonResetPass: typeof import("../components/Button/ResetPass.vue")['default']
export const LazyButtonSecondary: typeof import("../components/Button/Secondary.vue")['default']
export const LazyButtonSquare: typeof import("../components/Button/Square.vue")['default']
export const LazyButtonToggle copy: typeof import("../components/Button/Toggle copy.vue")['default']
export const LazyButtonToggle: typeof import("../components/Button/Toggle.vue")['default']
export const LazyButtonWithIcon: typeof import("../components/Button/WithIcon.vue")['default']
export const LazyButtonWithIcon2: typeof import("../components/Button/WithIcon2.vue")['default']
export const LazyCardsEventCategory: typeof import("../components/Cards/EventCategory.vue")['default']
export const LazyCardsGroupMsg: typeof import("../components/Cards/GroupMsg.vue")['default']
export const LazyCardsHost: typeof import("../components/Cards/Host.vue")['default']
export const LazyCardsLgProfile: typeof import("../components/Cards/LgProfile.vue")['default']
export const LazyCardsLocation: typeof import("../components/Cards/Location.vue")['default']
export const LazyCardsMessage: typeof import("../components/Cards/Message.vue")['default']
export const LazyCardsNotification: typeof import("../components/Cards/Notification.vue")['default']
export const LazyCardsNotification2: typeof import("../components/Cards/Notification2.vue")['default']
export const LazyCardsOffer: typeof import("../components/Cards/Offer.vue")['default']
export const LazyCardsProfile copy: typeof import("../components/Cards/Profile copy.vue")['default']
export const LazyCardsProfile: typeof import("../components/Cards/Profile.vue")['default']
export const LazyCardsProfile2: typeof import("../components/Cards/Profile2.vue")['default']
export const LazyCardsProfile3: typeof import("../components/Cards/Profile3.vue")['default']
export const LazyCommonActioncell: typeof import("../components/Common/Actioncell.vue")['default']
export const LazyCommonBreadcumb: typeof import("../components/Common/Breadcumb.vue")['default']
export const LazyCommonDotPaginator: typeof import("../components/Common/DotPaginator.vue")['default']
export const LazyCommonSimpleTimer: typeof import("../components/Common/SimpleTimer.vue")['default']
export const LazyCommonSlider: typeof import("../components/Common/Slider.vue")['default']
export const LazyCommonSpinner: typeof import("../components/Common/Spinner.vue")['default']
export const LazyCommonTab: typeof import("../components/Common/Tab.vue")['default']
export const LazyCommonTable: typeof import("../components/Common/Table.vue")['default']
export const LazyCommonTimer: typeof import("../components/Common/Timer.vue")['default']
export const LazyContainerAnimationPulse: typeof import("../components/Container/AnimationPulse.vue")['default']
export const LazyContainerCardScroller: typeof import("../components/Container/CardScroller.vue")['default']
export const LazyContainerDetails: typeof import("../components/Container/Details.vue")['default']
export const LazyContainerDiscount: typeof import("../components/Container/Discount.vue")['default']
export const LazyContainerEventDetails: typeof import("../components/Container/Event/Details.vue")['default']
export const LazyContainerEventDetailsCommon: typeof import("../components/Container/Event/DetailsCommon.vue")['default']
export const LazyContainerEventDetailsCommon2: typeof import("../components/Container/Event/DetailsCommon2.vue")['default']
export const LazyContainerEventDetailsSelfSmall: typeof import("../components/Container/Event/DetailsSelfSmall.vue")['default']
export const LazyContainerEventDetailsSmall: typeof import("../components/Container/Event/DetailsSmall.vue")['default']
export const LazyContainerEventEditSmall: typeof import("../components/Container/Event/EditSmall.vue")['default']
export const LazyContainerEventFinding: typeof import("../components/Container/Event/Finding.vue")['default']
export const LazyContainerEventParticipants: typeof import("../components/Container/Event/Participants.vue")['default']
export const LazyContainerEventParticipantsCommon: typeof import("../components/Container/Event/ParticipantsCommon.vue")['default']
export const LazyContainerEventSelfDetailsSmall: typeof import("../components/Container/Event/SelfDetailsSmall.vue")['default']
export const LazyContainerEventImg: typeof import("../components/Container/EventImg.vue")['default']
export const LazyContainerEventImg2: typeof import("../components/Container/EventImg2.vue")['default']
export const LazyContainerForgetPassword: typeof import("../components/Container/ForgetPassword.vue")['default']
export const LazyContainerFriendsGallary: typeof import("../components/Container/Friends/Gallary.vue")['default']
export const LazyContainerFriendsRequest: typeof import("../components/Container/Friends/Request.vue")['default']
export const LazyContainerGallarySlider: typeof import("../components/Container/GallarySlider.vue")['default']
export const LazyContainerGroupProfile: typeof import("../components/Container/GroupProfile.vue")['default']
export const LazyContainerHorizontal: typeof import("../components/Container/Horizontal.vue")['default']
export const LazyContainerHowWorks: typeof import("../components/Container/HowWorks.vue")['default']
export const LazyContainerImagesUploader: typeof import("../components/Container/ImagesUploader.vue")['default']
export const LazyContainerLogin: typeof import("../components/Container/Login.vue")['default']
export const LazyContainerMeetup: typeof import("../components/Container/Meetup.vue")['default']
export const LazyContainerMessageBox: typeof import("../components/Container/Message/Box.vue")['default']
export const LazyContainerProfile: typeof import("../components/Container/Profile.vue")['default']
export const LazyContainerProfileAbout: typeof import("../components/Container/Profile/About.vue")['default']
export const LazyContainerProfileDetailsSmall: typeof import("../components/Container/Profile/DetailsSmall.vue")['default']
export const LazyContainerProfileHabits: typeof import("../components/Container/Profile/Habits.vue")['default']
export const LazyContainerProfileImage: typeof import("../components/Container/Profile/Image.vue")['default']
export const LazyContainerProfileInterests: typeof import("../components/Container/Profile/Interests.vue")['default']
export const LazyContainerProfileLeftSideSection: typeof import("../components/Container/Profile/LeftSideSection.vue")['default']
export const LazyContainerProfileName: typeof import("../components/Container/Profile/Name.vue")['default']
export const LazyContainerProfilePhotos: typeof import("../components/Container/Profile/Photos.vue")['default']
export const LazyContainerProfilePublicDetailsSmall: typeof import("../components/Container/Profile/PublicDetailsSmall.vue")['default']
export const LazyContainerProfileSummery: typeof import("../components/Container/Profile/Summery.vue")['default']
export const LazyContainerProfileImagesUploader: typeof import("../components/Container/ProfileImagesUploader.vue")['default']
export const LazyContainerRegister copy: typeof import("../components/Container/Register copy.vue")['default']
export const LazyContainerRegister: typeof import("../components/Container/Register.vue")['default']
export const LazyContainerSlider: typeof import("../components/Container/Slider.vue")['default']
export const LazyContainerStories: typeof import("../components/Container/Stories.vue")['default']
export const LazyContainerTestimonial copy: typeof import("../components/Container/Testimonial copy.vue")['default']
export const LazyContainerTestimonial: typeof import("../components/Container/Testimonial.vue")['default']
export const LazyContainerUniversalSearch: typeof import("../components/Container/UniversalSearch.vue")['default']
export const LazyContainerUserDetails: typeof import("../components/Container/UserDetails.vue")['default']
export const LazyEventFilter: typeof import("../components/Event/Filter.vue")['default']
export const LazyEventGoingPeople: typeof import("../components/Event/GoingPeople.vue")['default']
export const LazyEventMap: typeof import("../components/Event/Map.vue")['default']
export const LazyEventSelf: typeof import("../components/Event/Self.vue")['default']
export const LazyEventSidebar: typeof import("../components/Event/Sidebar.vue")['default']
export const LazyFormAgepicker: typeof import("../components/Form/Agepicker.vue")['default']
export const LazyFormCheckbox: typeof import("../components/Form/Checkbox.vue")['default']
export const LazyFormCombobox: typeof import("../components/Form/Combobox.vue")['default']
export const LazyFormContainer: typeof import("../components/Form/Container.vue")['default']
export const LazyFormDate: typeof import("../components/Form/Date.vue")['default']
export const LazyFormDateTimepicker: typeof import("../components/Form/DateTimepicker.vue")['default']
export const LazyFormDatepicker: typeof import("../components/Form/Datepicker.vue")['default']
export const LazyFormDropdown: typeof import("../components/Form/Dropdown.vue")['default']
export const LazyFormEventCreationSelector: typeof import("../components/Form/EventCreationSelector.vue")['default']
export const LazyFormEventSelector: typeof import("../components/Form/EventSelector.vue")['default']
export const LazyFormEventSelector2: typeof import("../components/Form/EventSelector2.vue")['default']
export const LazyFormImage: typeof import("../components/Form/Image.vue")['default']
export const LazyFormImage2 copy: typeof import("../components/Form/Image2 copy.vue")['default']
export const LazyFormImage2: typeof import("../components/Form/Image2.vue")['default']
export const LazyFormImageSelector: typeof import("../components/Form/ImageSelector.vue")['default']
export const LazyFormInputNumber: typeof import("../components/Form/InputNumber.vue")['default']
export const LazyFormInputText: typeof import("../components/Form/InputText.vue")['default']
export const LazyFormInputText2: typeof import("../components/Form/InputText2.vue")['default']
export const LazyFormInputWithDropdown: typeof import("../components/Form/InputWithDropdown.vue")['default']
export const LazyFormMap copy 2: typeof import("../components/Form/Map copy 2.vue")['default']
export const LazyFormMap copy: typeof import("../components/Form/Map copy.vue")['default']
export const LazyFormMap: typeof import("../components/Form/Map.vue")['default']
export const LazyFormMap2: typeof import("../components/Form/Map2.vue")['default']
export const LazyFormMultipleSelect: typeof import("../components/Form/MultipleSelect.vue")['default']
export const LazyFormMultipleSelect2: typeof import("../components/Form/MultipleSelect2.vue")['default']
export const LazyFormOtp: typeof import("../components/Form/Otp.vue")['default']
export const LazyFormPassword: typeof import("../components/Form/Password.vue")['default']
export const LazyFormPermission: typeof import("../components/Form/Permission.vue")['default']
export const LazyFormPermission2: typeof import("../components/Form/Permission2.vue")['default']
export const LazyFormRangeSlider: typeof import("../components/Form/RangeSlider.vue")['default']
export const LazyFormSelector: typeof import("../components/Form/Selector.vue")['default']
export const LazyFormSelector2: typeof import("../components/Form/Selector2.vue")['default']
export const LazyFormSelector3: typeof import("../components/Form/Selector3.vue")['default']
export const LazyFormSelector4: typeof import("../components/Form/Selector4.vue")['default']
export const LazyFormSelector5: typeof import("../components/Form/Selector5.vue")['default']
export const LazyFormTextArea: typeof import("../components/Form/TextArea.vue")['default']
export const LazyFormTimeCombobox copy: typeof import("../components/Form/TimeCombobox copy.vue")['default']
export const LazyFormTimeCombobox: typeof import("../components/Form/TimeCombobox.vue")['default']
export const LazyFormTimepicker: typeof import("../components/Form/Timepicker.vue")['default']
export const LazyIconsCalender: typeof import("../components/Icons/Calender.vue")['default']
export const LazyIconsFriends: typeof import("../components/Icons/Friends.vue")['default']
export const LazyIconsMessage: typeof import("../components/Icons/Message.vue")['default']
export const LazyIconsNotification: typeof import("../components/Icons/Notification.vue")['default']
export const LazyIconsProfile: typeof import("../components/Icons/Profile.vue")['default']
export const LazyImgRecognizer copy 2: typeof import("../components/ImgRecognizer copy 2.vue")['default']
export const LazyImgRecognizer copy: typeof import("../components/ImgRecognizer copy.vue")['default']
export const LazyImgRecognizer: typeof import("../components/ImgRecognizer.vue")['default']
export const LazyImgTaker: typeof import("../components/ImgTaker.vue")['default']
export const LazyLoaderCircle: typeof import("../components/Loader/Circle.vue")['default']
export const LazyLoaderImgTake: typeof import("../components/Loader/ImgTake.vue")['default']
export const LazyLoaderUniversal: typeof import("../components/Loader/Universal.vue")['default']
export const LazyMap: typeof import("../components/Map.vue")['default']
export const LazyMarkerPopup: typeof import("../components/MarkerPopup.vue")['default']
export const LazyModalContainer: typeof import("../components/Modal/Container.vue")['default']
export const LazyModalDelete: typeof import("../components/Modal/Delete.vue")['default']
export const LazyModalFilter: typeof import("../components/Modal/Filter.vue")['default']
export const LazyModalPhotoviewer: typeof import("../components/Modal/Photoviewer.vue")['default']
export const LazyModalRegistrationContainer: typeof import("../components/Modal/RegistrationContainer.vue")['default']
export const LazyPageFooter: typeof import("../components/Page/Footer.vue")['default']
export const LazyPageHeader: typeof import("../components/Page/Header.vue")['default']
export const LazyPageHeaderSmall: typeof import("../components/Page/HeaderSmall.vue")['default']
export const LazyPageHerosection: typeof import("../components/Page/Herosection.vue")['default']
export const LazyPageHerosectionMobile: typeof import("../components/Page/HerosectionMobile.vue")['default']
export const LazyPageImageSlider: typeof import("../components/Page/ImageSlider.vue")['default']
export const LazyPageMenu: typeof import("../components/Page/Menu.vue")['default']
export const LazyPageMenu2: typeof import("../components/Page/Menu2.vue")['default']
export const LazyPageSearchbar: typeof import("../components/Page/Searchbar.vue")['default']
export const LazyPageSectionHeader: typeof import("../components/Page/SectionHeader.vue")['default']
export const LazyPageSelectionBar: typeof import("../components/Page/SelectionBar.vue")['default']
export const LazyPageSidebar: typeof import("../components/Page/Sidebar.vue")['default']
export const LazyPageSlider: typeof import("../components/Page/Slider.vue")['default']
export const LazyPageVerticalImageSlider: typeof import("../components/Page/VerticalImageSlider.vue")['default']
export const LazyPaginator: typeof import("../components/Paginator.vue")['default']
export const LazyPanelBottom: typeof import("../components/Panel/Bottom.vue")['default']
export const LazySimpleImgTaker: typeof import("../components/SimpleImgTaker.vue")['default']
export const LazySkeletonAbout: typeof import("../components/Skeleton/About.vue")['default']
export const LazySkeletonCards: typeof import("../components/Skeleton/Cards.vue")['default']
export const LazySkeletonEventImg: typeof import("../components/Skeleton/EventImg.vue")['default']
export const LazySkeletonFriends: typeof import("../components/Skeleton/Friends.vue")['default']
export const LazySkeletonInterests: typeof import("../components/Skeleton/Interests.vue")['default']
export const LazySkeletonMsgBox: typeof import("../components/Skeleton/MsgBox.vue")['default']
export const LazySkeletonMsgGroupCards: typeof import("../components/Skeleton/MsgGroupCards.vue")['default']
export const LazySkeletonName: typeof import("../components/Skeleton/Name.vue")['default']
export const LazySkeletonParticipants: typeof import("../components/Skeleton/Participants.vue")['default']
export const LazySkeletonParticipantsAndDelete: typeof import("../components/Skeleton/ParticipantsAndDelete.vue")['default']
export const LazySkeletonPhotos: typeof import("../components/Skeleton/Photos.vue")['default']
export const LazySkeletonProfileImg: typeof import("../components/Skeleton/ProfileImg.vue")['default']
export const LazySkeletonSlider: typeof import("../components/Skeleton/Slider.vue")['default']
export const LazySkeletonSpinner: typeof import("../components/Skeleton/Spinner.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyLCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LazyLCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LazyLControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LazyLControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LazyLControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LazyLControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LazyLControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LazyLFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LazyLGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LazyLIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LazyLImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LazyLLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LazyLMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LazyLMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LazyLPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LazyLPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LazyLPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LazyLRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LazyLTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LazyLTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LazyLWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyFormKit: typeof import("@formkit/vue")['FormKit']
export const LazyFormKitProvider: typeof import("@formkit/vue")['FormKitProvider']
export const LazyFormKitMessages: typeof import("@formkit/vue")['FormKitMessages']
export const LazyFormKitSummary: typeof import("@formkit/vue")['FormKitSummary']
export const LazyFormKitIcon: typeof import("@formkit/vue")['FormKitIcon']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
