// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/27/2024, 9:19:13 AM
const configMerger = require("D:/Web Development/nedbud/freundify/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Web Development/nedbud/freundify/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/nedbud/freundify/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/nedbud/freundify/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/nedbud/freundify/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/nedbud/freundify/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/nedbud/freundify/plugins/**/*.{js,ts,mjs}","D:/Web Development/nedbud/freundify/composables/**/*.{js,ts,mjs}","D:/Web Development/nedbud/freundify/utils/**/*.{js,ts,mjs}","D:/Web Development/nedbud/freundify/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/nedbud/freundify/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/nedbud/freundify/app.config.{js,ts,mjs}"] }));

module.exports = config
